name: Picmate
'on': [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'postgres:14.1'
        ports:
          - '5432:5432'
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Install dependencies
        run: sudo apt-get install libpq-dev
      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          rails db:create
          rails db:migrate
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: Run Rubocop
        run: |
          rubocop
      - name: Run tests
        run: rails test
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
